version: "2"
services:
  web:
    build: .
    ports:
      - "5100:5100"
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app/
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - .:/data/db
